import pymysql
conn = pymysql.connect(host='localhost', port=3306, user='root', passwd='', use_unicode=True, charset="utf8")
curr = conn.cursor()

curr.execute('CREATE DATABASE if not exists times_square;')

curr.execute('USE times_square')
curr.execute('DROP TABLE IF EXISTS times_data')
curr.execute('CREATE TABLE times_data (companyname varchar(255) NOT NULL, subindustry varchar(255) DEFAULT NULL, sub_subindustry varchar(255) DEFAULT NULL, phone varchar(255) DEFAULT NULL, website varchar(255) DEFAULT NULL, location varchar(255) DEFAULT NULL, PRIMARY KEY (companyname)) ENGINE=InnoDB DEFAULT CHARSET=utf8')

##All the following entries were imported directly through mySQL using a CSV File and the following code
"""
LOAD DATA LOCAL INFILE '/Users/sandraburneo/Desktop/NYU Spring 2015/Data Final Project/Timessquare data.csv'
INTO TABLE times_data
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
"""
curr.execute("INSERT INTO times_data VALUES ('1657 Broadway Deli, Ltd.','CafÃ© / Deli','','2129560099','','1651-1665 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('46 Bar (Paramount Hotel)','Bar / Lounge','','(212) 764-5500','http://www.nycparamount.com/','235 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('705 8th Avenue (8th Avenue Food Court)','CafÃ© / Deli','','','','705 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('810 Deli, Inc','CafÃ© / Deli','','2125414136','www.810deli.com','810 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('A Slice of New York Pizza','Quick Serve','Pizza','212-453-8970','','727 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Abondanza','CafÃ© / Deli','','(212) 938-1333','','146 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Amadeus Pizza','Quick Serve','Pizza','(212) 489-6187','www.rayspizzany.com','856 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Andy\'s Deli & Natural Foods','CafÃ© / Deli','','','','270 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Angus McIndoe Restaurant','Full Serve','American','(212) 221-9222','www.AngusMcIndoe.com','258 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Aoki','Full Serve','Japanese','(212) 956-2355 ','aokinyc.com','234 W 48th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Applebee\'s','Full Serve','American','(212) 262-4022','www.applebeesny.com','205 W 50th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Applebee\'s Neighborhood Grill and Bar','Full Serve','American','914-777-2331 Ext.116','www.ApplebeesNY.com','234 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Aramark Services, Inc.','Catering','','','','230 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('Aspen Social Club','Full Serve','American','(212) 221-7200 ','http://www.aspensocialclub.com/','157 W 47th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Auntie Anne\'s','Quick Serve','Fast Food','2127641542','www.auntieannes.com','664 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Aureole','Full Serve','American','2123191660','www.charliepalmer.com','1 Bryant Park')")
curr.execute("INSERT INTO times_data VALUES ('Avenue Restaurant @ Sheraton Hilton Hotel','Full Serve','American','(212) 581-3300','','811 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Azalea','Full Serve','Italian','(212) 262-0105','http://www.lunapienanyc.com/azalea_new/','224 W 51st St')")
curr.execute(r"INSERT INTO times_data VALUES ('B. Smith\'s Restaurant Row','Full Serve','American','(212) 315-1100','www.bsmith.com','320 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('B.B. King Blues Club & Grill','Full Serve','American','2129974144','www.bbkingblues.com','237 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Baja Fresh Mexican Grill','Quick Serve','Mexican','(212) 764-9084','','1441 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Bangkok House','Full Serve','Thai','(212) 541-5943','www.bangkokhouseny.com','260 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Bar 10','Bar / Lounge','','(212) 201-2764','www.westinny.com','270 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('Bar Americain','Full Serve','American','(212) 265-9700','www.baramerican.com','152 W 52nd St')")
curr.execute("INSERT INTO times_data VALUES ('Barbetta Restaurant','Full Serve','Italian','(212) 246-9171','barbettarestaurant.com','321 West 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Becco','Full Serve','Italian','(212) 397-7597','www.becconyc.com','355 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Bella Napoli','Full Serve','Italian','(212) 719-2819','','150 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Bella Vita','Full Serve','Italian','(212) 730-1479','www.bellavitanyc.com','221 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('Bistecca Fiorentina','Full Serve','Steakhouse','(212) 258-3232','www.bisteccafiorentinanyc.com','317 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Bistro Caterers','Catering','','','','155 W 51st St')")
curr.execute("INSERT INTO times_data VALUES ('Blockheads','Full Serve','Mexican','','','825 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Blue Fin','Full Serve','Seafood','(212) 918-1400','www.brguestrestaurants.com','W Times Square 1567 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Bluechili','Full Serve','Pan Asian','(212) 246-3330','www.bluechilinyc.com','251 W 51st St')")
curr.execute(r"INSERT INTO times_data VALUES ('Bobby Van\'s Steakhouse','Full Serve','American','','','120 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Bobby Vans','Full Serve','Steakhouse','212-957-5050','www.bobbyvans.com','135 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Bocca To Go Cucian Italiana','Full Serve','Italian','(212) 582-3000','www.boccatogo.com','135 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Bombay Masala Indian Restaurant','Full Serve','Indian','(212) 302-8150','www.bombaymasalany.com','148 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Bond 45','Full Serve','Italian','(212) 869-4545','www.bond45.com','154 West 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Bourbon Street Bar & Grille','Full Serve','Cajun','(212) 245-2030','www.bourbonny.com','346 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Brasserie 1605','Full Serve','American','(212) 315-6195','www.cpmanhattantimessquare.com','1605 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Brasserie Athena','Full Serve','French','(212) 399-1100','','300 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Brazil Brazil','Full Serve','Brazilian','(212) 957-4300','www.brazilbrazilrestaurant.com','328 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Brazil Grill','Full Serve','Brazilian','(212) 307-9449','http://cityinsights.com/newyork/brazilgrill.htm','787 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Broadway Joe Steakhouse','Full Serve','Steakhouse','(212) 246-6513','broadwayjoesteakhouse.com','315 W  46th St')")
curr.execute("INSERT INTO times_data VALUES ('Brooklyn Diner','Full Serve','Diner','(212) 265-5400','www.brooklyndiner.com','155 W 42rd St')")
curr.execute("INSERT INTO times_data VALUES ('Bubba Gump Shrimp Co.','Full Serve','Seafood','(212) 391-7100','www.bubbagump.com','209 avenida Fabricante Suite 200')")
curr.execute("INSERT INTO times_data VALUES ('CAFÃ‰ @ Times Square','CafÃ© / Deli','','(212) 391-7351','','159 W 51st St')")
curr.execute("INSERT INTO times_data VALUES ('Cafe Edison','Full Serve','American','(212) 840-5000','www.edisonhotelnyc.com','228 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Cafe Nicole @ Novotel','Full Serve','French','(951) 729-8661','http://www.novotel.com/gb/hotel-0753-novotel-new-york-times-square/restaurant.shtml','226 W 52nd St')")
curr.execute("INSERT INTO times_data VALUES ('Cafe O','Full Serve','American','(212) 852-4900','','30 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Cafe Un Deux Trois','Full Serve','French','(212) 354-4148','www.cafeuneuxtros.biz','123 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Caffe Cielo','Full Serve','Italian','212 246-9555','','881 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Capri Ristorante - CLOSED','Full Serve','Italian','212 582-5850','http://www.capri46.com','358 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Carmine\'s','Full Serve','Italian','(212) 221-3800','www.carminesnyc.com','200 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Carve: Unique Sandwiches','Quick Serve','American','(212) 730-4949','http://www.carve.cc/','768 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Carvel','Quick Serve','Dessert','212 391-6675','','1501 Broadway')")
curr.execute(r"INSERT INTO times_data VALUES ('Charley O\'s','Full Serve','American','2129770025','','713 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Chevys Fresh Mex','Full Serve','Mexican','(212) 302-4010','http://www.chevysny.com/EN/index.html','259 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Chicken Bar','Full Serve','American','(212) 245-5111','','717 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('China Gourmet','Full Serve','Chinese','(212) 246-8181','','877 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Chipotle Mexican grill','Quick Serve','Mexican','(212) 757-4312','www.chipotle.com','854 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Chock full o\' Nuts Cafe','CafÃ© / Deli','','2127645969','www.chockfullonuts.com','234 W 42nd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Chopp\'t','CafÃ© / Deli','','','','1460 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Ciro Trattoria','Full Serve','Italian','(212) 307-5484','www.cirotrattorianyc.com','813 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('City Chow','CafÃ© / Deli','','(212) 445-0600','www.blueradishgroup.com','1633 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Club House CafÃ©','Full Serve','Spanish','(212) 354-3838','','155 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Cold Stone Creamery/ Tim Horton\'s','Quick Serve','Dessert','2123981882','www.coldstonecreamery.com','243 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Coldstone Creamery','Quick Serve','Dessert','(212) 398-1882','www.coldstonecreamery.com','1501 Broadway, Suite 1604')")
curr.execute(r"INSERT INTO times_data VALUES ('Connolly\'s Pub And Restaurant','Bar / Lounge','','(212) 597-5126','www.ConnollysPubAndRestaurant.com','121 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Cosi','CafÃ© / Deli','','2123972674','www.cosiny.com','1633 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Cosmic Diner','Full Serve','Diner','212 333-5888','','888 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Cranberry Gourmet','CafÃ© / Deli','','(212) 730-9495','','115 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Crown Deli','Full Serve','Italian','(212) 265-1414','','1678 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Crumbs','Quick Serve','Dessert','2127949800','http://crumbs.com/','1675 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Cyber Cafe','CafÃ© / Deli','','','','250 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Da Marino','Full Serve','Italian','(212) 541-6601','','220 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Da Rosina Ristorante Italiano','Full Serve','Italian','(212) 977-7373','www.darosina.com','342 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Dale & Thomas Popcorn','Quick Serve','Other','(212) 581-1872','www.daleandthomas.com','1592 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Dallas BBQ','Full Serve','Barbecue','2128732004','','27 W 72nd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Daniela\'s Trattoria','Full Serve','Italian','212 869-3585','','728 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Danny\'s Deli','Full Serve','Italian','(212) 921-1200','','224 W 47th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Danny\'s Grand Sea Palace','Full Serve','Seafood','(212) 265-8130','','346 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Dave & Buster\'s','Full Serve','American','(646) 495-2015','www.daveandbusters.com','2481 Manana Drive')")
curr.execute(r"INSERT INTO times_data VALUES ('David\'s Potbelly Stove Cafe','CafÃ© / Deli','','(212) 626-9000','','1501 Broadway')")
curr.execute(r"INSERT INTO times_data VALUES ('Deacon Brodie\'s Tavern','Bar / Lounge','','(212) 262-1452','','370 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Dean & Deluca','CafÃ© / Deli','','(212) 869-6890','www.deandeluca.com','560 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Deli / CafÃ©','CafÃ© / Deli','','(212) 541-4136','http://www.810deli.com/','810 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Dervish Turkish Restaurant','Full Serve','Turkish','212 997-0070','www.dervishrestaurant.com','146 W 47th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Dippin\' Dots','Quick Serve','Dessert','','www.dippindots.com','234 W 42nd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Domino\'s Pizza','Quick Serve','Pizza','2129440400','','230 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('Dunhill Cafe','Full Serve','American','(212) 944-8484','','109 W 45th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Dunkin\' Donuts','Coffee','','(212) 757-4617','','210 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Duvel Bar Rest','Full Serve','Belgian','(212) 768-0200','www.bxcafe.com','125 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('EASY INTERNET CAFE TIME SQUARE LLC','CafÃ© / Deli','','','','258 W 42nd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Ellen\'s Stardust Diner','Full Serve','American','(212) 956-5151','www.ellensstardustdiner.com','1650 Broadway')")
curr.execute(r"INSERT INTO times_data VALUES ('Emmett O\'Lunney\'s','Bar / Lounge','','(212) 957-5100','www.emmettolunneys.com','210 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Encore Restaurant @ Marriott Marquis','Full Serve','American','(212) 704-8849','www.NYMarriottMarquis.com','1535 Broadway 5th Floor')")
curr.execute("INSERT INTO times_data VALUES ('Europa CafÃ©','CafÃ© / Deli','','(212) 664-1820 x14','','218 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Europa Cafe','CafÃ© / Deli','','212-239-0160','www.euorpacafe.com','3 Times Sq')")
curr.execute("INSERT INTO times_data VALUES ('EZ Deil and NY Nail Land','CafÃ© / Deli','','(212) 333-5650','','1625 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('F & H Liquor Center Inc','Consumables','Beverages','(212) 247-4991','','810 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Famous Dave\'s B-B-Q','Full Serve','Barbecue','(212) 764-1899','http://www.famousdaves.com/','169 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Famous Famiglia Pizza','Quick Serve','Pizza','(212) 382-3030 ','','686 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Famous Famiglia Pizzeria','Quick Serve','Pizza','(212) 333-4646','www.famousfamiglia.com','1630 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Firebird Restaurant','Full Serve','Russian','(212) 586-0244','firebirdrestaurant.com','365 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Frankie & Johnnie\'s Steakhouse','Full Serve','Steakhouse','(212) 997-9494','http://www.frankieandjohnnies.com/','269 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Fu Ying','Quick Serve','Chinese','(212) 489-5008 ','','811 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Gallagher\'s Steak House','Full Serve','Steakhouse','(212) 245-5336','www.gallaghersnysteakhouse.com','228 W 52nd St')")
curr.execute("INSERT INTO times_data VALUES ('Gingers Restaurant','Full Serve','American','(212) 403-6371','www.nyc.doubletreehotels.com','1568 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Glass House Tavern','Full Serve','American','(212) 730-4800','http://glasshousetavern.com','252 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Godiva Chocolatier, Inc.','Quick Serve','Dessert','(212) 840-6758','www.godiva.com','1460 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Gourmet New York','CafÃ© / Deli','','','','680 Eighth Ave'),('Grand Sichuan','Full Serve','Chinese','','','368 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Green Emporium','CafÃ© / Deli','','2124591924','','791 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Green Symphony','Full Serve','Organic','(212) 391-4747 ','','255 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('H&B Heartland Burgers','Full Serve','American','(646) 366-0235','http://www.heartlandbrewery.com/Times_Square.php','127 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('Haagen-Dazs','Quick Serve','Dessert','','www.haagen-dazs.com','761-779 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Haggis Inc','Full Serve','Scottish','2128408413','','120 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Hale & Hearty','CafÃ© / Deli','','2122219666','www.haleandhearty.com','745 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Hard Rock Cafe','Full Serve','American','2123433355','www.hardrockcafe.com','1501 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Harmony View','Bar / Lounge','','(212) 957-5100','www.harmonyview.com/','210 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Haru','Full Serve','Japanese','(212) 398-9810','','205 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('Havana Central','Full Serve','Cuban','2123987440','www.havanacentral.com','151 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Hawaiian Tropic Zone','Full Serve','American','212-626-7312','www.hawaiiantropiczone.com','729 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Heartland Brewery','Full Serve','American','212-366-0235','www.heartlandbrewery.com','127 W 43rd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Houlihan\'s Restaurant & Bar','Full Serve','American','2126267316','www.houlihans.com','729 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Hourglass Tavern','Full Serve','','(212) 265-2060','http://www.hourglasstavern.com','373 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Howard Johnson\'s Cafe\'','CafÃ© / Deli','','','','1551-1553 Broadway')")
curr.execute(r"INSERT INTO times_data VALUES ('Hudson\'s Sports Bar & Grill','Quick Serve','American','(212) 841-6551','','811 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Hurley\'s Steak and Seafood','Full Serve','Steakhouse','(212) 765-8981','','232 W 48th St')")
curr.execute("INSERT INTO times_data VALUES ('Ichi Masa Japanese Sushi','Full Serve','Japanese','(212) 315-4800','http://ichimasany.com/','825 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Inakaya','Full Serve','Japanese','(212) 354-2130','','20 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Insieme @ The Michaelangelo','Full Serve','Italian','(212) 582-1310','www.restaurantinsieme.com','777 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Iroha','Full Serve','Japanese','212 398-9049','','152 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Italia Mia Pizza','Full Serve','Pizza','(212) 265-1414','','1674 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Jade Terrace','Full Serve','Chinese','(212) 398-3800 ','','268 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Jamba Juice','CafÃ© / Deli','','(212) 582-1915','www.jambajuice.com','1700 17th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Jimmy\'s Corner','Bar / Lounge','','(212) 221-9510','','140 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Joe Allen','Full Serve','American','(212) 581-6464','www.joeallenrestaurant.com','326 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('John\'s Pizzeria','Full Serve','Pizza','(212) 391-7560','www.johnpizzerianyc.com','260 W 44th St')")
curr.execute(r"INSERT INTO times_data VALUES ('John\'s Shanghai','Full Serve','Chinese','(212) 869-9183','','144 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Joshua Tree - CLOSED','Full Serve','American','(212) 489-1920','http://www.joshuatreebarnyc.com/','368 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Juniors Restaurant','Full Serve','American','212-302-2000','www.juniorscheescake.com','1515 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Just Pies Inc','Quick Serve','Dessert','2127217001','','260 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Katen Sushi Bar','Full Serve','Japanese','(212) 398-1900 ','','1525 Broadway 8th Floor')")
curr.execute("INSERT INTO times_data VALUES ('KFC, Tim Horton, Pizza Hut','Coffee','','(212) 767-8347','','761 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Kodama Sushi','Full Serve','Japanese','(212) 582-8065 ','http://kodamajapanesenyc.com/','301 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('La Masseria','Full Serve','Italian','(212) 582-2111','http://www.lamasserianyc.com/','235 W 48th St')")
curr.execute("INSERT INTO times_data VALUES ('La Rivista Ristorante','Full Serve','Italian','212-245-1707','www.larivistanyc.com','313 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Langan\'s Bar & Restaurant','Full Serve','American','(212) 869-5482','www.langans.com','150 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Latitude','Full Serve','American','(212) 245-3034','','783 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Lattanzi Restaurant','Full Serve','Italian','(212) 315-0980','www.lattanzinyc.com','359 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Laxmi Corp. Newsstand','CafÃ© / Deli','','','','877 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Le Bernardin','Full Serve','French','2125541515','www.le-bernardin.com','155 51st\n')")
curr.execute("INSERT INTO times_data VALUES ('Le Marais','Full Serve','French','(212) 869-0900','www.lemarais.net','150 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Le Rivage','Full Serve','French','(212) 765-7374','www.lerivagenyc.com','340 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Library Bar','Full Serve','American','(212) 827-4183','','235 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Lp Food & Beverage Inc/Oceo','Catering','','2122626236','www.oceo.com','224 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Lucky Star Cafe','Full Serve','American','(201) 838-9269','','250 W 43rd St')")
curr.execute("INSERT INTO times_data VALUES ('LyBane Wine Bar','Full Serve','Italian','(212) 582-2012','','709 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Majestic Delication CafÃ©','CafÃ© / Deli','','2125818249','www.majesticdeli.com','750 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Mama Sbarro\'s','Quick Serve','Pizza','(212) 768-4194','www.sbarro.com','1606 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Manchu WOK','Quick Serve','Chinese','','www.manchuwok.com','234 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Margon Restaurant Co.','Full Serve','Cuban','(212) 354-5013','','136 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Mars 2112','Full Serve','American','2125822112','www.mars2112.com','1633 Broadway, Suite #B')")
curr.execute(r"INSERT INTO times_data VALUES ('Martini\'s Restaurant','Full Serve','Italian','(212) 767-1146','','810 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Maxie\'s Delicatessen','CafÃ© / Deli','','(212) 398-1118','','723 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('McDonald\'s','Quick Serve','Fast Food','2125865530','','1651 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Mean Fiddler, The','Bar / Lounge','','(212) 354-2950','','266 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Meson Sevilla Ristorante','Full Serve','Spanish','(212) 262-5890','mesonsevilla.com','344 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Metro Deli/ Ranch #1','CafÃ© / Deli','','(212) 768-1111','','141 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('Metromet, Inc.','Catering','','','http://www.metromet.com/metromet/index.php','224 West 49th St Suite 1619')")
curr.execute("INSERT INTO times_data VALUES ('Mi Nidito (Cantina Mexicana)','Full Serve','Mexican','(212) 265-0022','','852 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Midtown Gourmet Deli','CafÃ© / Deli','','(212) 586-6433','','840 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Minar Indian Restaurant','Full Serve','Indian','(212) 398-4600','www.minarny.com','138 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Moda @ Flatotel','Full Serve','Italian','(212) 887-9880','','135 W 52nd St')")
curr.execute("INSERT INTO times_data VALUES ('Montenapo Restaurant','Full Serve','Italian','(212) 764-7663 ','montenaporestaurant.com','250 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('N Valenti Restaurant Associates','Catering','','2127898145','','120 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Nan King Chinese Cuisine','Full Serve','Chinese','(212) 586-3100','','1632 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Natsumi Restaurant, Bar & Lounge','Full Serve','Japanese','(212) 258-2988','www.natsumnyc.com','226 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('New York Bagel Company','CafÃ© / Deli','','2123977720','www.networkbeyond.com','1674 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('NIOS Restaurant @ Muse Hotel','Full Serve','American','212 485-2400','districtnyc.com','130 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('O\'Brien\'s Bar and Grill','Bar / Lounge','American','(212) 391-1516','','134 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('O\'Flaherty\'s Ale House & Restaurant','Full Serve','American','(212) 581-9366','www.oflahertynyc.com','334 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('O\'Lunney\'s Times Square Pub','Full Serve','American','212 840-6688','www.olunneys.com','145 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Oceo','Full Serve','Afghan','212 262-6236','','224 West 29th St')")
curr.execute("INSERT INTO times_data VALUES ('Ocha Sushi','Full Serve','Japanese','2125813198','','350 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Off Broadway Deli/ Pizza','CafÃ© / Deli','','','','726 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Olive Garden Italian Restaurant','Full Serve','Italian','2123333254','www.olivegarden.com','2 Times Sq')")
curr.execute("INSERT INTO times_data VALUES ('Olympic Restaurant','Full Serve','American','(212) 956-3230','','807 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Orso','Full Serve','Italian','212-489-7212','www.orsorestaurant.com','322 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Osteria Al Doge','Full Serve','Italian','(212) 944-3643','www.osteria_doge.com','142 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Palm Restaurant','Full Serve','Steakhouse','(212) 333-7256','http://www.thepalm.com/','250 W 50th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Papa John\'s/Subway','Quick Serve','Pizza','2122451900','www.papajohns.com','765 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Paramount Cafe','CafÃ© / Deli','','2123916675','','1501 Broadway, Suite #2009')")
curr.execute("INSERT INTO times_data VALUES ('Pasta Lovers Trattoria','Full Serve','Italian','212 819-1155','www.pastaloversnyc.com','142 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Patina Restaurant Group','Catering','','(212) 789-8100','','120 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('Patzeria Pizza','Quick Serve','Pizza','(212) 575-7646','http://www.patzeriaspizzanyc.com','231 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Pax Foods','CafÃ© / Deli','','(212) 399-9100','www.paxfood.com','740 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Pax World','CafÃ© / Deli','','(800) 767-1729','http://www.paxworld.com/','225 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Pearls','Full Serve','Chinese','(212) 582-7380','','732 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Pergola des Artistes','Full Serve','French','2123027500','pergoladesartistes.com','252 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Piano Due','Quick Serve','American','(212) 399-9400','http://www.pianoduenyc.net/','151 W 51st St')")
curr.execute(r"INSERT INTO times_data VALUES ('Pig \'N\' Whistle','Full Serve','American','(212) 302-0112','www.pignwhistlets.com','165 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Pigalle','Full Serve','French','(212) 489-2233','www.pigallenyc.com','790 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Pinnacle Bar','Full Serve','American','212-642-2607','www1.hilton.com/en_US/hi/hotel/NYCTSHF-Hilton-Times-Square-New-York/dining.do','234 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Pizza Hut','Quick Serve','Pizza','2127678347','www.pizzahut.com','761-779 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Planet Hollywood','Full Serve','American','(212) 333-7827','www.planethollywoodintl.com','1540 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Playwright Bar And Restaurant','Full Serve','American','(212) 262-9263','www.playwrighttavern.com','202 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('Playwright Celtic Pub','Bar / Lounge','','(212) 354-8404','http://www.playwrightcelticpubnyc.com/','732 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Pomaire','Full Serve','Chilean','(212) 956-3055','www.pomairenyc.com','371 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Pongsri Thai Restaurant','Full Serve','Thai','2125823392','','244 W 48th St')")
curr.execute("INSERT INTO times_data VALUES ('Port Gourmet Deli','CafÃ© / Deli','','(212) 245-3168','','681 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Pret a Manger','CafÃ© / Deli','','(212) 489-6458','','135 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Pronto Pizza-Lemlen Pizza','Full Serve','Pizza','(212) 221-8886','','135 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('Qdoba Mexican Grill','Quick Serve','Mexican','2127670040','www.qdoba.com','135 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Ranch 1','Quick Serve','Fast Food','2129561111','','141 W 41st St')")
curr.execute(r"INSERT INTO times_data VALUES ('Ray\'s Famous Pizza','Quick Serve','Pizza','(212) 956-7297','www.rayspizzany.com','736 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Red Lobster','Full Serve','Seafood','2127306706','www.redlobster.com','5 Times Sq')")
curr.execute("INSERT INTO times_data VALUES ('Restaurant','Full Serve','American','2128690900','www.lemarais.net','155 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Restaurant Charlotte @ Millennium Broadway Hotel','Full Serve','American','212 789-7508','millenniumbroadway.com','145 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Rino Trattoria','Full Serve','Italian','(212) 307-0666','www.rinotrattoria.com','877 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Ritz Bar & Lounge','Bar / Lounge','','(212) 977-3884','','369 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Robert Emmett\'s Bar & Restaurant','Full Serve','American','(212) 302-9999','www.robertemmetts.com','694 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Rosie O\'Grady\'s Saloon','Full Serve','American','212-582-2975','','800 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Rosie O\'Grady\'s Steakhouse','Full Serve','Steakhouse','212 869-0600','www.rosieogradystimessquare.com','149 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Roxy Deli','CafÃ© / Deli','','212-921-3333','www.roxydeli.com','1565 Broadway')")
curr.execute(r"INSERT INTO times_data VALUES ('Ruby Foo\'s','Full Serve','Pan Asian','(212) 489-5600','www.brguestrestaurants.com','750 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Ruby Tuesday','Full Serve','American','(212) 382-3898 ','http://www.rubytuesday.com/','7 Times Sq')")
curr.execute(r"INSERT INTO times_data VALUES ('Ruby\'s Diner','Full Serve','Diner','','www.rubys.com','234 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Rum House','Bar / Lounge','','(212) 869-3005','','228 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Russian Samovar Restaurant','Full Serve','Russian','(212) 757-0168','','256 W 52nd St')")
curr.execute("INSERT INTO times_data VALUES ('Russian Vodka Room','Full Serve','Russian','(212) 307-5835 ','http://russianvodkaroom.com/','265 W 52nd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Russo\'s Steak and Pasta','Full Serve','American','(212) 621-8523','shearton.com/manhattan','790 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Ruth\'s Chris Steak House','Full Serve','Steakhouse','212 245-9600','','148 W 51st St')")
curr.execute("INSERT INTO times_data VALUES ('Saigon 48','Full Serve','Vietnamese','(212) 247-8669','','234 W 48th St')")
curr.execute("INSERT INTO times_data VALUES ('Saju French Bistro @ Hotel Mela','Full Serve','French','212-977-saju','www.sajunyc.com','120 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('San Leone','Full Serve','Italian','(212) 265-1414','','1674 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Sangria 46','Full Serve','Spanish','212-581-8482','www.sangria46.com','338 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Sapporo','Full Serve','Japanese','212 869-8972','','152 W 49th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Sardi\'s Restaurant','Full Serve','American','(212) 221-8440','www.sardis.com','234-236 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Sbarro','Quick Serve','Pizza','2122219725','','701 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Scarlatto','Full Serve','Italian','212 730-4535','scarlattonyc.com','250 W 47th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Schnipper\'s Quality Kitchen','Full Serve','American','(212) 921-2400','http://www.schnippers.com/','20 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Scott Alliang-Demonstration Room','Catering','','','','130 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Scott Alling-Convivial Catering','Catering','','','','130 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Scotts Food Court','Quick Serve','American','2127681111','','141 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('Seasons','Full Serve','American','(212) 586-2257','','888 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Serafina @ Time Hotel','Full Serve','Italian','212','','22 W 49th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Shula\'s Steakhouse','Full Serve','Steakhouse','2122012776','http://www.donshula.com','250 W 43rd St')")
curr.execute(r"INSERT INTO times_data VALUES ('Smith\'s Bar & Restaurant','Full Serve','American','(212) 246-3268','www.smithsbar.com','701 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Smokehouse','Full Serve','Italian','','www.baldoriamo.com','249 W 48th St')")
curr.execute("INSERT INTO times_data VALUES ('Social Bar NYC & Latitude Bar Grill','Full Serve','American','(212) 459-0643','www.manhattan.crowneplaza.com','795 Eighth Avenue')")
curr.execute(r"INSERT INTO times_data VALUES ('Sofia\'s','Full Serve','Italian','(212) 719-5799','www.sofiasny.com','221 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Sombrero','Full Serve','Mexican','(212) 586-4853','www.sombreroRestaurant.com','303 W 48th St')")
curr.execute("INSERT INTO times_data VALUES ('Sosa Borella','Full Serve','Argentinian','(212) 262-8282','http://www.sosaborella.com/','832 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Spice Fusion','Full Serve','Indian','212-757-8100','www.myspicefusion.com','777 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Spotlight Times Square','Full Serve','American','2129776773','','1604-1610 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('St. Andrews Restaurant and Bar','Bar / Lounge','','(212) 840-8413','www.standrewsnyc.com','142 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Starbucks','Coffee','','2122467699','www.starbucks.com','871-879 Eight Ave')")
curr.execute("INSERT INTO times_data VALUES ('Starbucks (@ Marriott)','Coffee','','(212) 398-1900','http://www.starbucks.com/store/14269/','1535 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Starlite Deli','CafÃ© / Deli','','(212) 840-1859','','212 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Subway','Quick Serve','Fast Food','2122651822','','214 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Sunrise Deli','CafÃ© / Deli','','2122216490','','1441 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Sushi of Gari','Full Serve','Japanese','(212) 957-0046','www.sushiofgari.com','347 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Swing 46 Jazz and Supper Club','Full Serve','American','(212) 262-9554','www.swing46.com','349 W 46th St')")
curr.execute(r"INSERT INTO times_data VALUES ('T.G.I. Friday\'s','Full Serve','American','2127678349','www.tgifridays.com','761 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Tad\'s Steak House','Full Serve','Steakhouse','(212) 767-8348','','701 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Tad\'s Steakhouse','Full Serve','Steakhouse','(212) 382-1164','','761 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('Tasti D-Lite','Quick Serve','Dessert','(212) 977-4000','','1588 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Teriyaki Boy (month to month)','Quick Serve','Japanese','(212) 265-8181','','732 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('TGI Friday\'s','Full Serve','American','2129447352','www.fridays.com','1552 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Thalia Kitchen','Full Serve','Italian','(212) 399-4444','http://www.restaurantthalia.com/','828 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('The Alicart Restaurant Group','Catering','','2126759790','http://www.alicart.com/','1501 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('The House of Brews','Full Serve','American','','http://www.houseofbrewsny.com/','302 W 51st St')")
curr.execute("INSERT INTO times_data VALUES ('The Library @ Paramount Hotel','Full Serve','American','212 827-4183','www.paramountNewYork.solmelia.com','235 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('The Long Room','Bar / Lounge','','(212) 997-3933','www.thelongroomnyc.com','120 44th St\n')")
curr.execute("INSERT INTO times_data VALUES ('The Perfect Pint','Bar / Lounge','','(212) 354-1099','www.theperfectpintnyc.com','123 W 45th St')")
curr.execute("INSERT INTO times_data VALUES ('The Two Times Square Restaurant','Full Serve','American','(212) 261-5200','www.twotimessquarerestaurant.com','714 Seventh Ave')")
curr.execute("INSERT INTO times_data VALUES ('The View Restaurant & Lounge @ Marriott Marquis','Full Serve','American','(212) 704-8849','www.NYMarriottMarquis.com','1535 Broadway 48th Floor')")
curr.execute("INSERT INTO times_data VALUES ('The Whiskey','Bar / Lounge','','2129307444','www.midnightoilbars.com','1567 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Time Square Deli','CafÃ© / Deli','','(212) 840-7983','','1501 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('Times Deli CafÃ©','CafÃ© / Deli','','212 944-1234','','158 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Times Square Hot Bagels','CafÃ© / Deli','','(212) 997-7300','','200 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Toloache','Full Serve','Mexican','(212) 581-1818 ','www.toloachenyc.com','251 W 50th St')")
curr.execute("INSERT INTO times_data VALUES ('Tom and Toon','Full Serve','Thai','','','245 W 51st St')")
curr.execute("INSERT INTO times_data VALUES ('Tonic Sports Bar & Restaurant','Full Serve','American','(212) 382-1059','www.thetonicbar.com','727 Seventh Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Tony\'s Di Napoli','Full Serve','Italian','(212) 221-0100','www.tonysnyc.com','147 W 43th St')")
curr.execute("INSERT INTO times_data VALUES ('Tramonti','Full Serve','Italian','(212) 974-7464','','364 W 46th St')")
curr.execute("INSERT INTO times_data VALUES ('Trattoria Dopo Teatro','Full Serve','Italian','(212) 869-2849','dopoteatro.com','125 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Trattoria Trecolori','Full Serve','Italian','(212) 997-4540','','254 W 47th St')")
curr.execute(r"INSERT INTO times_data VALUES ('Uncle A\'s Mini Mart','CafÃ© / Deli','','(212) 921-7185','','220 W 41st St')")
curr.execute("INSERT INTO times_data VALUES ('vacant (8th Avenue Pavilion Flea Market)','Consumables','Non-beverages','','','675 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Vacant (former CafÃ© Groppi)','CafÃ© / Deli','','(212) 221-0082','','148 W 49th St')")
curr.execute("INSERT INTO times_data VALUES ('vacant (former starbucks)','Coffee','','2122451936','www.starbucks.com','1600 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('VACANT (frmerly Starbucks)','Coffee','','','','1600 Broadway ')")
curr.execute("INSERT INTO times_data VALUES ('Vacant (Juan Valdez Coffee)','Coffee','','212 871-7515','','1451 Broadway')")
curr.execute("INSERT INTO times_data VALUES ('vacant (Red Mango)','Quick Serve','Dessert','(212) 315-0101','http://www.redmangousa.com/default.html','723 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Victor\'s Cafe','CafÃ© / Deli','','(212) 586-7714 ','www.victorscafe.com','236 W 52nd St')")
curr.execute("INSERT INTO times_data VALUES ('Villa Pizza','Quick Serve','Pizza','(212) 302-2941','www.villapizza.com','662 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Virgils Real Barbecue','Full Serve','Barbecue','(212) 921-9494','www.virgilsbbq.com','152 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('Virtigo Cafe Llc','CafÃ© / Deli','','2122219454','','234 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Viva Pancho','Full Serve','Mexican','(212) 944-9747','','156 W 44th St')")
curr.execute("INSERT INTO times_data VALUES ('World of Nuts and Ice Cream','Quick Serve','Dessert','(212) 245-0398','www.worldofnutsandicecream.com','888 Eighth Ave')")
curr.execute("INSERT INTO times_data VALUES ('Y & H Grocery','CafÃ© / Deli','','(212) 840-1659','','150 W 47th St')")
curr.execute("INSERT INTO times_data VALUES ('Yoshinoya Beef Bowl Restaurant','Full Serve','Japanese','(212) 703-9940','http://www.yoshinoyausa.com','255 W 42nd St')")
curr.execute("INSERT INTO times_data VALUES ('Z Deli-Pizzeria','Quick Serve','Pizza','(212) 315-1659','','803 Eighth Ave')")
curr.execute(r"INSERT INTO times_data VALUES ('Zheng\'s Lucky Sunday Garden','Quick Serve','Chinese','(212) 459-3607','http://www.luckysundayny.com/','856 Eighth Ave')")

curr.execute('DROP TABLE IF EXISTS address')
curr.execute('CREATE TABLE Address (idAddress MEDIUMINT NOT NULL AUTO_INCREMENT, Location VARCHAR(225), PRIMARY KEY(idAddress))')
curr.execute('INSERT INTO address (Location) SELECT DISTINCT location FROM times_data')
curr.execute('DROP TABLE IF EXISTS restaurant')
curr.execute('CREATE TABLE restaurant (idRestaurant MEDIUMINT NOT NULL AUTO_INCREMENT, CompanyName varchar(225) DEFAULT NULL, PRIMARY KEY (idRestaurant))')   
curr.execute('INSERT INTO restaurant (CompanyName) SELECT companyname FROM times_data')
curr.execute('DROP TABLE IF EXISTS sub_subindustry')
curr.execute('CREATE TABLE sub_subindustry (idSub_subindustry MEDIUMINT NOT NULL AUTO_INCREMENT, Sub_subindustry varchar(225) DEFAULT NULL, PRIMARY KEY (idSub_subindustry))')
curr.execute('INSERT INTO sub_subindustry (Sub_subindustry) SELECT DISTINCT Sub_subindustry FROM times_data')
curr.execute('DROP TABLE IF EXISTS subindustry')
curr.execute('CREATE TABLE subindustry (idSubindustry MEDIUMINT NOT NULL AUTO_INCREMENT, Subindustry varchar(225) DEFAULT NULL, PRIMARY KEY (idSubindustry))')           
curr.execute('INSERT INTO subindustry (Subindustry) SELECT DISTINCT Subindustry FROM times_data')

curr.execute('DROP TABLE IF EXISTS Intermediate_Rest_SubInd')
curr.execute('CREATE TABLE Intermediate_Rest_SubInd AS (SELECT idRestaurant, SubindustryID FROM (SELECT si.idSubindustry AS SubindustryID, td.companyname AS CompanyName FROM subindustry AS si INNER JOIN times_data AS td ON si.Subindustry=td.Subindustry) AS x INNER JOIN restaurant as r ON x.CompanyName=r.CompanyName)')
curr.execute('DROP TABLE IF EXISTS Intermediate_Rest_Subsub')
curr.execute('CREATE TABLE Intermediate_Rest_Subsub AS (SELECT idRestaurant, SubSubindustry FROM (SELECT ssi.idSub_subindustry AS SubSubindustry, td.companyname AS CompanyName FROM sub_subindustry AS ssi INNER JOIN times_data as td ON ssi.Sub_Subindustry=td.sub_subindustry) AS x INNER JOIN restaurant as r ON x.CompanyName=r.CompanyName)')

curr.execute('DROP TABLE IF EXISTS Intermediate_Rest_Location')
curr.execute('CREATE TABLE Intermediate_Rest_Location AS (SELECT idRestaurant, idAddress FROM (SELECT a.idAddress AS idAddress, td.companyname AS CompanyName FROM address AS a INNER JOIN times_data AS td ON a.Location=td.location) AS x INNER JOIN restaurant as r ON x.CompanyName=r.CompanyName)')

conn.commit()
